import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import SideBar from "./_components/SideBar";
import NavBar from "./_components/NavigationBar";
import { ScrollArea } from "@/components/ui/scroll-area";

export const metadata: Metadata = {
  title: "Osu Reccomender",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <TRPCReactProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <div className="flex h-full flex-row">
            <SideBar
              sidebarItems={[
                {
                  name: "Home",
                  href: "/",
                  symbol: "/HouseIcon.svg",
                },
                {
                  name: "Popular",
                  href: "/popular",
                  symbol: "/FlameIcon.svg",
                },
                {
                  name: "Players",
                  href: "/players",
                  symbol: "/UsersIcon.svg",
                },
              ]}
            />
            <div className="flex h-screen w-full flex-col">
              <NavBar />
              <ScrollArea className="h-full">{children}</ScrollArea>
            </div>
          </div>
        </body>
      </html>
    </TRPCReactProvider>
  );
}
